---
# tasks file for XPRESSI

- name: Validar el status de lo servicios XPRESSI
  win_shell: |
    $v = Get-Service | Where-Object {($_.Name -eq "{{ xpressi[0] }}") -or ($_.Name -eq "{{ xpressi[1] }}")} | Select -Property DisplayName,Status
    $v
  register: result_status

- name: Imprimir status de los servicios XPRESSI
  debug:
    msg:
     - " **** INFORMATIVO **** " 
     - " Estado actual de los servicios XPRESSI : "
     - "{{ result_status.stdout_lines }}"

- block: 
    - name: Detener los servicios XPRESSI
      win_shell: |
         Get-Service | Where-Object {($_.Name -eq "{{ xpressi[0] }}") -or ($_.Name -eq "{{ xpressi[1] }}")} | Stop-Service
      register: result_stop
    
    - name: Validar status de lo servicios XPRESSI
      win_shell: |
         Get-Service | Where-Object {($_.Name -eq "{{ xpressi[0] }}") -or ($_.Name -eq "{{ xpressi[1] }}")} | Select -Property DisplayName,Status
      register: result_status

    - name: Imprimir mensaje correcto
      debug:
        msg:  
         - " ¡¡ CORRECTO !!"
         - " Estado actual de los servicios XPRESSI : "
         - "{{ result_status.stdout_lines }}"
         - " "
         - " "
         - " Se detuvieron correctamente los servicios XPRESSI ... "

  rescue:
    - name:  Validar el status de los servicios XPRESSI
      win_shell: Get-Service | Where-Object {($_.Name -eq "{{ xpressi[0] }}") -or ($_.Name -eq "{{ xpressi[1] }}")} | Select -Property DisplayName,Status
      register: result_status

    - name: Validar licencias
      win_find:
         paths: "{{ ruta_lic }}"
         file_type: directory
      register: result_licencias


    
    - name: Imprimir mensaje error
      debug:
        msg:
         - " ¡¡ ERROR !! "
         - " Los servicios XPRESSI no se detuvieron correctamente ."
         - " Estado actual de los servicios XPRESSI: "
         - "{{ result_status.stdout_lines }}"
         - " "  
         - " Se valida que existe {{ result_licencias.files | length }} carpetas temporales de licencias " 
         - " Favor de contactar e informar al analista .... "
    
    - fail:
         

- block:
    - name: Iniciar los servicios XPRESSI
      win_shell: | 
         Get-Service | Where-Object {($_.Name -eq "{{ xpressi[0] }}") -or ($_.Name -eq "{{ xpressi[1] }}")} | Start-Service
      register: result_start
    
    - name: Validar el status de los servicios XPRESSI
      win_shell: |
         Get-Service | Where-Object {($_.Name -eq "{{ xpressi[0] }}") -or ($_.Name -eq "{{ xpressi[1] }}")} | Select -Property DisplayName,Status
      register: result_status2
    

    - name: Imprimir mensaje correcto
      debug:
        msg:
           - " ¡¡ CORRECTO !! "
           - " Se iniciaron correctamente los servicios XPRESSI ...."
           - "  "
           - " Estado actual de los servicios XPRESSI : "
           - "{{ result_status2.stdout_lines }}"
           - "  "
           - "  "
           - " Se aplico correctamente el WorkAround. Favor de mandar a validar ... " 

  rescue:
    - name: Validar el status de los servicios XPRESSI
      win_shell: Get-Service | Where-Object {($_.Name -eq "{{ xpressi[0] }}") -or ($_.Name -eq "{{ xpressi[1] }}")} | Select -Property DisplayName,Status
      register: result_status3
    
    - name: Validar licencias
      win_find:
        paths: "{{ ruta_lic }}"
        file_type: directory
      register: result_licencias2

    - name: Imprimir mensaje error
      debug:
        msg:
         - " ¡¡ ERROR !! "
         - " No se pudo INICIAR correctamente los servicios XPRESSI ."
         - " Estado actual de los servicios XPRESSI : "
         - "{{ result_status3.stdout_lines }}"
         - "  "
         - "  "
         - " Se valida que existe {{ result_licencias2 | length }} carpetas temporales de licencias. "
         - " Favor de contactar e informar al analista ....... "
